version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    labels: [dependencies, github-actions]
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    labels: [dependencies, npm]
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: increase

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    target-branch: main
    labels: [dependencies, rust]
    commit-message:
      prefix: "chore(deps)"
