server {
    listen 80;
    listen [::]:80;
    server_name lridrop.isamarin.xyz;

    root /var/www/lridrop.isamarin.xyz;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        allow all;
    }

    location / {
        return 301 https://lridrop.isamarin.xyz$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name lridrop.isamarin.xyz;

    ssl_certificate     /etc/letsencrypt/live/lridrop.isamarin.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lridrop.isamarin.xyz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;

    root /var/www/lridrop.isamarin.xyz;
    index index.html;

    gzip on;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml font/woff2;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Served-By "luma-twc" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|ico|png|jpg|jpeg|svg|webp|woff2)$ {
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }
}
